### ISSUE TITLE
getImage.py is not working?

### ISSUE THREAD

**Issue by LeoCannon** [brianrho/GT5X#3]
i recently found your GT5X and i gave it a try.
i tested some of your Sketch examples and most of them work except to GetImage.py

so here is a thing first i would give:
- BaudRate 9600
- COM7
-Fingerprint Scanner - TTL (GT-521F52)
-Arduino Uno R3

i did download your GT5X library via Github and save it to Desktop folder, then manually add the .ZIP Library to Arduino IDE(for additional description)

then according to our gmail conversation, i should first upload the sketch **"image_to_pc"**  then run the Python code saved in your library.
so i did as you said. 1st, i open File > Example > Image_to_PC sketch. then i upload it to my Arduino Uno R3. it uploaded successfully(in image, top and bottom left). 2nd, i open my Visual Studio Code and open your **GetImage.py** the one i saved at Desktop Folder. i run it, then edit the necessary command. press 1 then put COM7 and BaudRate9600. then press 2. i enter the name/path of my file(MyPrint.bmp. green circle in right) then press enter. However it said **Invalid Port Settings!**  and Image **Extraction Failed!** .

 now, the problem here is i cannot make any progress in getting image of the scanned fingerprint. while there is MyPrint.bmp being created, that bmp is empty and no fingerprint. i did try Baudrate 57600 but the problem remain persisting. it always say "Invalid Port Settings!" when my port is COM7. i haven't edit any of your code except i simply remove the "." that keep looping while waiting for finger to be touch, but nothing ever change. specially your GetImage.py
 
 is there anything wrong?
 thank you for your github contribution!
![image](https://user-images.githubusercontent.com/102912637/161433909-9bd8123a-fd3b-4125-8f52-bd3743e981c1.png)

**Comment by brianrho** [comment]
Let's try to see what the exception is -- make the following changes in the script:

```
- except Exception:
-     print('Invalid port settings!')
+ except Exception as e:
+     print('Invalid port settings: ', e)
```

Also, when you're running this script, make sure that the Serial Monitor **isn't** open, either in Visual Studio or in the Arduino IDE -- two applications cannot open the same port simultaneously AFAIK.

And, try to run the script from Command Prompt or Powershell, rather than using Visual Studio's builtin terminal.

**Comment by LeoCannon** [comment]
![image](https://user-images.githubusercontent.com/102912637/161666735-bddbf1da-ca3c-4356-92e4-3cba9e4414d0.png)
Hi i did what you said. i upload the sketch, then close my IDE, then run the Python Code. now i am not stuck on "invalid port settings!"

i can now press 2, then the next thing that appears to me  **"Found Fingerprint Sensor! Place your finger"**. however there is still a problem. if i put my finger, it say it is scanning but in the end it says "sending image...." then "Timeout. Image Extraction Failed!"(see the terminal on left below)

to see if the python or the Arduino Sketch has the problem, i try to rerun the Arduino Sketch code alone. as you can see on the right it say "image stream complete"...which i guess is successful. but when it comes to python file, the error is "Timeout". i assume the Python file is still having problem(i could be wrong)

any possible problem?

**Comment by brianrho** [comment]
Try changing the print() here to see how many bytes had been read so far:

```
              if not byte:
-                   print("Timeout!")
+                   print("Timeout: ", i)
                    out.close()  # close port and file
```

Again, make sure all your Serial Monitors/programs are closed when you run the script.
And again, try to run the script from Command Prompt or Powershell, rather than using Visual Studio's builtin terminal.

**Comment by brianrho** [comment]
Is your issue fixed? Can you now get images from the sensor?
